-- 1.0 local/acceptance baseline: normalize lifecycle metadata on legacy tables.
ALTER TABLE app_metadata ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE auth_sessions
  ADD COLUMN updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE roles ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE user_roles
  ADD COLUMN updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE menus ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE permissions ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE iam_policies
  ADD COLUMN updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE iam_data_scopes
  ADD COLUMN updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE auth_audit_events
  ADD COLUMN updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE setting_versions
  ADD COLUMN created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE tenants ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE organizations ADD COLUMN deleted_at TIMESTAMP(6) NULL;
ALTER TABLE file_objects
  ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  ADD COLUMN deleted_at DATETIME(6) NULL;
