ALTER TABLE file_objects DROP COLUMN deleted_at, DROP COLUMN updated_at;
ALTER TABLE organizations DROP COLUMN deleted_at;
ALTER TABLE tenants DROP COLUMN deleted_at;
ALTER TABLE setting_versions DROP COLUMN deleted_at, DROP COLUMN created_at;
ALTER TABLE auth_audit_events DROP COLUMN deleted_at, DROP COLUMN updated_at;
ALTER TABLE iam_data_scopes DROP COLUMN deleted_at, DROP COLUMN updated_at;
ALTER TABLE iam_policies DROP COLUMN deleted_at, DROP COLUMN updated_at;
ALTER TABLE permissions DROP COLUMN deleted_at;
ALTER TABLE menus DROP COLUMN deleted_at;
ALTER TABLE user_roles DROP COLUMN deleted_at, DROP COLUMN updated_at;
ALTER TABLE roles DROP COLUMN deleted_at;
ALTER TABLE auth_sessions DROP COLUMN deleted_at, DROP COLUMN updated_at;
ALTER TABLE users DROP COLUMN deleted_at;
ALTER TABLE app_metadata DROP COLUMN deleted_at;
