ALTER TABLE file_objects DROP COLUMN IF EXISTS deleted_at, DROP COLUMN IF EXISTS updated_at;
ALTER TABLE organizations DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE tenants DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE setting_versions DROP COLUMN IF EXISTS deleted_at, DROP COLUMN IF EXISTS created_at;
ALTER TABLE auth_audit_events DROP COLUMN IF EXISTS deleted_at, DROP COLUMN IF EXISTS updated_at;
ALTER TABLE iam_data_scopes DROP COLUMN IF EXISTS deleted_at, DROP COLUMN IF EXISTS updated_at;
ALTER TABLE iam_policies DROP COLUMN IF EXISTS deleted_at, DROP COLUMN IF EXISTS updated_at;
ALTER TABLE permissions DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE menus DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE user_roles DROP COLUMN IF EXISTS deleted_at, DROP COLUMN IF EXISTS updated_at;
ALTER TABLE roles DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE auth_sessions DROP COLUMN IF EXISTS deleted_at, DROP COLUMN IF EXISTS updated_at;
ALTER TABLE users DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE app_metadata DROP COLUMN IF EXISTS deleted_at;
