ALTER TABLE setting_versions DROP COLUMN IF EXISTS org_id, DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE auth_audit_events DROP COLUMN IF EXISTS org_id, DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE auth_sessions DROP COLUMN IF EXISTS org_id, DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE iam_data_scopes DROP COLUMN IF EXISTS org_id, DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE iam_policies DROP COLUMN IF EXISTS org_id, DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE permissions DROP COLUMN IF EXISTS org_id, DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE menus DROP COLUMN IF EXISTS org_id, DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE roles DROP COLUMN IF EXISTS org_id, DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE user_roles DROP COLUMN IF EXISTS org_id, DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE users DROP COLUMN IF EXISTS org_id, DROP COLUMN IF EXISTS tenant_id;

DROP TABLE IF EXISTS organizations;
DROP TABLE IF EXISTS tenants;
